#! /usr/bin/env python3

ENV_DEBUG = False
SAMPLE_SAVE_PATH = "./train-data"
ROUND_FLAG_1 = "cards:"
ROUND_FLAG_2 = "card-process:"
LAST_ROUND_NO = 6
N_POLICY_ACTION = 309
N_KICKER_ACTION = 28
POLICY_MODEL_PARENT_PATH = "./ddz/Supervised-Model/policy-model/"
POLICY_MODEL_SAVE_PATH = POLICY_MODEL_PARENT_PATH + "policy"
POLICY_META_SAVE_PATH = POLICY_MODEL_SAVE_PATH + ".meta"
KICKER_MODEL_PARENT_PATH = "./ddz/Supervised-Model/kicker-model/"
KICKER_MODEL_SAVE_PATH = KICKER_MODEL_PARENT_PATH + "kicker"
KICKER_META_SAVE_PATH = KICKER_MODEL_SAVE_PATH + ".meta"